import axios from 'axios'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import agent from './api/agent'
interface SampleModel {
  id: number;
  name: string
}
const Home: NextPage = () => {
  const [samples, setSamples] = useState<SampleModel[] | null>(null)
  const [name, setName] = useState("")
  useEffect(() => {
   // agent.Sample.list().then(res => setSamples(res))
    //fetch('api/hello').then(async response => await response.json().then(res => setName(res.name)))
    fetch('api/sampleList').then(async response => await response.json().then(res => setSamples(res)))
    axios.get('api/hello').then(res => setName(res.data.name))
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{name}</h1>
        {samples?.map(s => <div key={s.id}>{s.name}</div>)}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
